services:
  server:
    build: .
    ports:
      - "2828:2828"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json