# fly.toml app configuration file generated for nodejs-filetransfer-test-server on 2025-06-22T08:08:05+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodejs-filetransfer-test-server'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 2828
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[deploy]
  strategy = "immediate"
